import { ArrowRight, CalendarDays, Layers3, Target, Users } from "lucide-react";

const strategyRows = [["Primary goal", "Build authority", Target], ["Target audience", "Operators & founders", Users], ["Weekly focus", "Teach the method behind outcomes", CalendarDays], ["Content mix", "Proof · Opinion · Personal", Layers3]] as const;
const nextBestMoves = [["Share your client onboarding framework", "Authority"], ["Turn your latest case study into a proof post", "Trust"], ["Reduce AI tools content this week", "Positioning"]];

export function ProductStrategyMoves() {
  return <section aria-labelledby="product-strategy-moves-heading" className="bg-[#f8fbfd] py-24 sm:py-28 lg:py-36"><div className="marketing-container grid items-center gap-14 lg:grid-cols-[minmax(0,1.22fr)_minmax(0,0.78fr)] lg:gap-20"><StrategyMovesPreview /><div className="max-w-xl lg:order-2"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em] text-[#3977a9]">From insight to action</p><h2 id="product-strategy-moves-heading" className="text-balance mt-5 text-4xl font-semibold leading-[1.02] tracking-[-0.06em] text-[#101826] sm:text-5xl lg:text-[3.8rem]">Clonao turns diagnosis into direction.</h2><p className="mt-6 max-w-lg text-base leading-7 text-[#647384] sm:text-lg sm:leading-8">It builds your strategy, then prioritizes the actions most likely to move your personal brand forward.</p></div></div></section>;
}

function StrategyMovesPreview() {
  return <div aria-label="Strategy leading into next best moves" className="relative"><div className="grid items-center gap-8 lg:grid-cols-[minmax(0,0.85fr)_4.5rem_minmax(0,1.15fr)] lg:gap-5"><section aria-labelledby="strategy-preview-heading"><p className="text-[0.62rem] font-semibold uppercase tracking-[0.18em] text-[#3977a9]">Built from diagnosis</p><h3 id="strategy-preview-heading" className="mt-2 text-2xl font-semibold tracking-[-0.05em] text-[#101826]">Strategy</h3><div className="mt-5 divide-y divide-[#cad9e3] border-y border-[#cad9e3]">{strategyRows.map(([label, value, Icon]) => <div key={label} className="flex items-center gap-3 py-3.5"><Icon className="size-4 shrink-0 text-[#3977a9]" strokeWidth={1.6} aria-hidden="true" /><p className="text-sm leading-5"><span className="text-[#7893a6]">{label}</span><span className="mx-2 text-[#b5c4ce]">/</span><span className="font-medium text-[#26394d]">{value}</span></p></div>)}</div></section><div className="relative flex items-center justify-center" aria-hidden="true"><span className="h-px w-full bg-[#71899a]/55" /><ArrowRight className="absolute size-4 bg-[#f8fbfd] px-0.5 text-[#3977a9]" strokeWidth={1.6} /></div><section aria-labelledby="next-best-moves-preview-heading"><p className="text-[0.62rem] font-semibold uppercase tracking-[0.18em] text-[#2563a6]">Prioritized for you</p><h3 id="next-best-moves-preview-heading" className="mt-2 text-2xl font-semibold tracking-[-0.05em] text-[#101826]">Next Best Moves</h3><div className="mt-5 divide-y divide-[#cad9e3] border-y border-[#cad9e3]">{nextBestMoves.map(([move, goal], index) => <div key={move} className="grid grid-cols-[2rem_minmax(0,1fr)] gap-3 py-4"><span className="text-lg font-semibold tracking-[-0.04em] text-[#4d9cf3]">{String(index + 1).padStart(2, "0")}</span><p className="text-sm font-semibold leading-5 text-[#172638]"><span>{move}</span><span className="mt-1 block text-xs font-medium uppercase tracking-[0.1em] text-[#3977a9]">Goal: {goal}</span></p></div>)}</div></section></div></div>;
}
