import { ArrowRight, Network } from "lucide-react";

const graphCategories = ["Expertise", "Stories", "Opinions", "Proof", "Audience", "Offers", "Topics"];
const diagnosisSignals = [["Strong association", "AI Automation"], ["Missing proof", "AI implementation results"], ["Overused topic", "AI tools"], ["Weak positioning", "Founder Strategy"]];

export function ProductBrandIntelligence() {
  return <section aria-labelledby="product-brand-intelligence-heading" className="bg-[#f8fbfd] py-24 sm:py-28 lg:py-36"><div className="marketing-container grid items-center gap-14 lg:grid-cols-[minmax(0,0.78fr)_minmax(0,1.22fr)] lg:gap-20"><div className="max-w-xl"><p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em] text-[#3977a9]">Brand intelligence</p><h2 id="product-brand-intelligence-heading" className="text-balance mt-5 text-4xl font-semibold leading-[1.02] tracking-[-0.06em] text-[#101826] sm:text-5xl lg:text-[3.8rem]">Clonao learns who you are before it tells you what to do.</h2><p className="mt-6 max-w-lg text-base leading-7 text-[#647384] sm:text-lg sm:leading-8">Your expertise, stories, opinions, proof, audience, offers, topics, and performance become a living Brand Graph that Clonao can diagnose and use across the product.</p></div><BrandIntelligencePreview /></div></section>;
}

function BrandIntelligencePreview() {
  return <div aria-label="Brand Graph to diagnosis relationship" className="relative"><div className="grid items-center gap-8 lg:grid-cols-[minmax(0,0.9fr)_4.5rem_minmax(0,1.1fr)] lg:gap-5"><section aria-labelledby="brand-graph-preview-heading"><div className="flex items-center gap-2.5"><Network className="size-5 text-[#101826]" strokeWidth={1.55} aria-hidden="true" /><h3 id="brand-graph-preview-heading" className="text-xl font-semibold tracking-[-0.045em] text-[#101826]">Brand Graph</h3></div><p className="mt-2 text-sm leading-6 text-[#7893a6]">The context Clonao learns from.</p><div className="mt-5 flex flex-wrap gap-x-3 gap-y-2 border-y border-[#cad9e3] py-4">{graphCategories.map((category) => <span key={category} className="text-sm font-medium text-[#26394d]">{category}</span>)}</div></section><div className="relative flex items-center justify-center" aria-hidden="true"><span className="h-px w-full bg-[#71899a]/55" /><ArrowRight className="absolute size-4 bg-[#f8fbfd] px-0.5 text-[#3977a9]" strokeWidth={1.6} /></div><section aria-labelledby="diagnosis-preview-heading"><div className="flex items-center justify-between gap-3"><div><p className="text-[0.62rem] font-semibold uppercase tracking-[0.18em] text-[#3977a9]">What Clonao sees</p><h3 id="diagnosis-preview-heading" className="mt-2 text-xl font-semibold tracking-[-0.045em] text-[#101826]">Diagnosis</h3></div><span className="text-[0.62rem] font-semibold uppercase tracking-[0.14em] text-[#7893a6]">01 / 04</span></div><div className="mt-5 divide-y divide-[#cad9e3] border-y border-[#cad9e3]">{diagnosisSignals.map(([label, value], index) => <div key={label} className="grid grid-cols-[1.2rem_minmax(0,1fr)] gap-3 py-3.5 sm:grid-cols-[1.5rem_minmax(0,1fr)]"><span className="text-xs font-medium text-[#8aa0b0]">{String(index + 1).padStart(2, "0")}</span><p className="text-sm leading-5 text-[#26394d]"><span className="font-medium text-[#7893a6]">{label}</span><span className="mx-1.5 text-[#b5c4ce]">—</span><span className="font-semibold text-[#172638]">{value}</span></p></div>)}</div></section></div></div>;
}
